#1. Ask a number from the user 10 times
num1 = int(input("Enter a number: "))
num2 = int(input("Enter a number: "))
num3 = int(input("Enter a number: "))
num4 = int(input("Enter a number: "))
num5 = int(input("Enter a number: "))
num6 = int(input("Enter a number: "))
num7 = int(input("Enter a number: "))
num8 = int(input("Enter a number: "))
num9 = int(input("Enter a number: "))
num10 = int(input("Enter a number: "))